importScripts("shared.js");
(function(){
'use strict';var ZN=function(a,b){return new $APP.oe(null,function(){var c=$APP.D(b);if(c){var d=$APP.E(c),e=a.j?a.j(d):a.call(null,d),f=$APP.he(d,$APP.zh(function(g){return $APP.H.C(e,a.j?a.j(g):a.call(null,g))},$APP.F(c)));return $APP.he(f,ZN(a,new $APP.oe(null,function(){return $APP.Af($APP.G(f),c)},null)))}return null},null)},$N=function(a,b,c){if($APP.ce(c)){var d=$APP.Ie($APP.Pn,$APP.Df.C(a,c));return b.j?b.j(d):b.call(null,d)}return $APP.Wf(c)?(d=new $APP.Kd(function(){var e=$APP.rb(c);return a.j?
a.j(e):a.call(null,e)}(),function(){var e=$APP.sb(c);return a.j?a.j(e):a.call(null,e)}()),b.j?b.j(d):b.call(null,d)):$APP.zd(c)?(d=$APP.Gh($APP.Df.C(a,c)),b.j?b.j(d):b.call(null,d)):$APP.td(c)?(d=$APP.Ra(function(e,f){return $APP.ee.C(e,a.j?a.j(f):a.call(null,f))},c,c),b.j?b.j(d):b.call(null,d)):$APP.od(c)?(d=$APP.Dg.C($APP.ad(c),$APP.Df.C(a,c)),b.j?b.j(d):b.call(null,d)):b.j?b.j(c):b.call(null,c)},bO=function(a){function b(c){var d=$APP.O(c,0,null);c=$APP.O(c,1,null);return typeof d==="string"?new $APP.T(null,
2,5,$APP.U,[$APP.Vh.j(d),c],null):new $APP.T(null,2,5,$APP.U,[d,c],null)}return aO(function(c){return $APP.sd(c)?$APP.Dg.C($APP.S,$APP.Df.C(b,c)):c},a)},cO=function(a){return $APP.p($APP.p(a)?$APP.gd(a.toArray):a)?a.toArray():a},fO=function(a){a=$APP.Df.C(function(c){return c===1?1:0},a);var b=$APP.Ra(function(c,d){var e=$APP.$c(c);var f=$APP.p(e)?e:new $APP.n(null,2,[dO,0,eO,0],null);e=dO.j(f)+(d===1?1:0);d=eO.j(f)+(d===1?0:1);return $APP.ee.C(c,new $APP.n(null,2,[dO,e,eO,d],null))},$APP.Hf,$APP.fe(a));
b=$APP.fe(b);return new $APP.T(null,3,5,$APP.U,[$APP.ye($APP.Df.C(dO,b)),$APP.ye($APP.Df.C(eO,b)),$APP.ye(a)],null)},kO=function(a,b,c,d,e){var f=$APP.Qe(a);a=$APP.P(f,gO);var g=$APP.P(f,hO),k=$APP.P(f,iO);f=$APP.P(f,jO);var l=$APP.E(b);c=c[l];d=d[l];l=c+d;if(l<2)return new $APP.n(null,4,[gO,a,hO,g,iO,k,jO,f],null);var m=$APP.Td($APP.Jn,$APP.Df.C(function(r){return e[r]},b));b=$APP.G(b);var q=c*b/l;return new $APP.n(null,4,[gO,a+(m-q),hO,l>1?g+d*c*b*(l-b)/(l*l*(l-1)):g,iO,k+(m-q),jO,f+d/l*q],null)},
lO=function(a,b,c){if(($APP.wt.j?$APP.wt.j(b):$APP.wt.call(null,b))<3)return new $APP.T(null,2,5,$APP.U,[0,1],null);var d=$APP.yt.j?$APP.yt.j(a):$APP.yt.call(null,a),e=a.take(d).toArray();a=b.take(d).toArray();c=c.take(d).toArray();c=fO(c);var f=$APP.O(c,0,null),g=$APP.O(c,1,null),k=$APP.O(c,2,null);c=$APP.vf(function(l,m){return $APP.p(m)?l:null},a);if($APP.nd(c))return new $APP.T(null,2,5,$APP.U,[0,1],null);c=$APP.Ra(function(l,m){return kO(l,m,f,g,k)},new $APP.n(null,4,[gO,0,hO,0,iO,0,jO,0],null),
ZN(function(l){return e[l]},c));return hO.j(c)<=0?new $APP.T(null,2,5,$APP.U,[0,1],null):new $APP.T(null,2,5,$APP.U,[-gO.j(c)/Math.sqrt(hO.j(c)),jO.j(c)>0?Math.exp(iO.j(c)/jO.j(c)):1],null)},mO=function(a,b,c){var d=a.size;if(d===0)return 1;var e=$APP.yt.j?$APP.yt.j(a):$APP.yt.call(null,a);a=a.take(e).toArray();b=b.take(e).toArray();b=$APP.Ff(function(f){var g=$APP.O(f,0,null),k=$APP.O(f,1,null);$APP.O(f,2,null);return $APP.p(k)?g<=c:k},$APP.Df.Y($APP.Wn,a,b,$APP.Fh(0,d,1)));return $APP.Ra(function(f,
g){$APP.O(g,0,null);$APP.O(g,1,null);g=$APP.O(g,2,null);return f*(1-1/(d-g))},1,b)},nO=function(a,b,c,d){var e=b.random(a),f=function(){var g=$APP.tt.j?$APP.tt.j(e):$APP.tt.call(null,e);return $APP.pt.C?$APP.pt.C(g,-1):$APP.pt.call(null,g,-1)}();a=function(){var g=1/d;return $APP.st.C?$APP.st.C(f,g):$APP.st.call(null,f,g)}();return $APP.pt.C?$APP.pt.C(a,c):$APP.pt.call(null,a,c)},oO=function(a,b,c){var d=$APP.Qe(a);a=$APP.P(d,$APP.Xq);d=$APP.P(d,$APP.gr);return nO(b,c,a,d)},pO=function(a,b,c){var d=
$APP.Qe(a),e=$APP.P(d,$APP.Aq);a=$APP.P(d,$APP.rs);var f=$APP.P(d,$APP.wq);d=c.random(b).toArray();b=nO(b,c,a,f).toArray();b=$APP.Df.J(function(g,k){return g<e?Infinity:k},d,b);b=$APP.ye(b);return $APP.Z.j?$APP.Z.j(b):$APP.Z.call(null,b)},qO=function(a,b,c){a=$APP.Qe(a);var d=$APP.P(a,$APP.Aq),e=$APP.P(a,$APP.rs),f=$APP.P(a,$APP.wq),g=$APP.P(a,$APP.Eq);a=c.random(b).toArray();e=nO(b,c,e,f).toArray();var k=g/12;b=c.random(b).toArray();b=$APP.Df.Y(function(l,m,q){return l<d?k>0?-Math.log(q)/k:Infinity:
m},a,e,b);b=$APP.ye(b);return $APP.Z.j?$APP.Z.j(b):$APP.Z.call(null,b)},rO=function(a,b,c){switch($APP.qp.j(a)){case "weibull":return nO(b,c,$APP.Oo.j(a),$APP.Gp.j(a));case "cure":return pO(a,b,c);case "leaky":return qO(a,b,c);default:return null}},vO=function(a,b,c,d){for(var e=new $APP.n(null,3,[sO,$APP.rf(0),tO,$APP.rf(0),uO,$APP.rf(0)],null),f=0;;)if(f<d){var g=b[f],k=c[f];k<=Math.max($APP.No.j(a)-g,0)&&$APP.ri.C(sO.j(e),$APP.Hc);k<=Math.max($APP.Ep.j(a)-g,0)&&$APP.ri.C(tO.j(e),$APP.Hc);$APP.p($APP.zr.j(a))&&
k<=Math.max($APP.ur.j(a)-g,0)&&$APP.ri.C(uO.j(e),$APP.Hc);f+=1}else break;return new $APP.n(null,3,[sO,$APP.Lc(sO.j(e)),tO,$APP.Lc(tO.j(e)),uO,$APP.Lc(uO.j(e))],null)},wO=function(a,b){var c=$APP.Qe(b),d=$APP.P(c,sO);b=$APP.P(c,tO);var e=$APP.P(c,uO);c=Math.abs(d-$APP.Up.j(a))<=$APP.Fr.j(a);var f=Math.abs(b-$APP.Hp.j(a))<=$APP.xq.j(a);d=b-d;var g=$APP.Hp.j(a)-$APP.Up.j(a);d=Math.abs(d-g);b=$APP.Ia($APP.zr.j(a))?!0:Math.abs(e-$APP.tq.j(a))<=$APP.qs.j(a)&&Math.abs(e-b-($APP.tq.j(a)-$APP.Hp.j(a)))<=
$APP.Eo.j(a);return c&&f&&d<=$APP.Vo.j(a)&&b},AO=function(a,b){var c=$APP.Qe(b);b=$APP.P(c,xO);var d=$APP.P(c,yO);c=$APP.P(c,zO);d=$APP.Z.j?$APP.Z.j(d):$APP.Z.call(null,d);c=$APP.Z.j?$APP.Z.j(c):$APP.Z.call(null,c);var e=b<$APP.ks.j(a);return e?(b=b>$APP.rp.j(a))?(b=$APP.zo.j(a)>0?mO(d,c,$APP.zo.j(a))>.5:!0)?$APP.Zo.j(a)>0?(b=$APP.xt.j?$APP.xt.j(d):$APP.xt.call(null,d),Math.abs(b-$APP.Zo.j(a))<=$APP.gp.j(a)):!0:b:b:e},DO=function(a,b,c,d){for(var e=new Float64Array(b),f=new Int32Array(b),g=0;;)if(g<
b){var k=Math.max(a-c[g],0),l=d[g];e[g]=Math.min(l,k);f[g]=l<=k?1:0;g+=1}else break;return new $APP.n(null,2,[BO,e,CO,f],null)},IO=function(a,b,c,d,e){for(var f=[],g=0;;)if(g<e){var k=b[g]+c[g];$APP.p(Number.isFinite(k))&&f.push(k);g+=1}else break;f.sort(function(m,q){return m-q});var l=f.length>=$APP.Jq.j(a);f=l?f[$APP.Jq.j(a)-1]:NaN;g=$APP.p(function(){var m=$APP.Tp.j(a);return $APP.p(m)?l:m}())?f>=function(){var m=EO.j(a);return $APP.p(m)?m:63}()-$APP.fq.j(a):!0;return l&&g?(b=DO(f,e,b,c),c=$APP.Qe(b),
b=$APP.P(c,BO),c=$APP.P(c,CO),b=lO($APP.Z.j?$APP.Z.j(b):$APP.Z.call(null,b),$APP.Z.j?$APP.Z.j(c):$APP.Z.call(null,c),$APP.Z.j?$APP.Z.j(d):$APP.Z.call(null,d)),d=$APP.O(b,0,null),b=$APP.O(b,1,null),new $APP.n(null,4,[FO,!0,GO,f,$APP.Qo,b,HO,d],null)):new $APP.n(null,4,[FO,!1,GO,f,$APP.Qo,NaN,HO,NaN],null)},JO=function(a,b,c){for(var d=$APP.G(b),e=0;;)if(e<d)e<c&&(a[b[e]]=1),e+=1;else break},KO=function(a,b,c,d,e){for(var f=0,g=0,k=0;;)if(f<a)b[f]===0?(e[f]=c[g],g+=1,f+=1):(e[f]=d[k],k+=1,f+=1);else break},
OO=function(a,b,c,d,e){var f=new Float64Array(c),g=new Int8Array(c),k=new Float64Array(c),l=[];e=$APP.D(e);for(var m=null,q=0,r=0;;)if(r<q){var v=m.sa(null,r),w=$APP.O(v,0,null),y=$APP.O(v,1,null);v=$APP.O(v,2,null);if(v>0){w=$APP.D(cO(b.uniform(w,y,v)));y=null;for(var A=v=0;;)if(A<v){var C=y.sa(null,A);l.push(C);A+=1}else if(w=$APP.D(w))y=w,$APP.vd(y)?(w=$APP.Yb(y),A=$APP.$b(y),y=w,v=$APP.G(w),w=A):(w=$APP.E(y),l.push(w),w=$APP.F(y),y=null,v=0),A=0;else break}r+=1}else if(e=$APP.D(e)){if($APP.vd(e))q=
$APP.Yb(e),e=$APP.$b(e),m=q,q=$APP.G(q);else{r=$APP.E(e);m=$APP.O(r,0,null);q=$APP.O(r,1,null);r=$APP.O(r,2,null);if(r>0)for(m=$APP.D(cO(b.uniform(m,q,r))),q=null,w=r=0;;)if(w<r)y=q.sa(null,w),l.push(y),w+=1;else if(m=$APP.D(m))q=m,$APP.vd(q)?(m=$APP.Yb(q),w=$APP.$b(q),q=m,r=$APP.G(m),m=w):(m=$APP.E(q),l.push(m),m=$APP.F(q),q=null,r=0),w=0;else break;e=$APP.F(e);m=null;q=0}r=0}else break;l.sort(function(I,J){return I-J});e=cO(function(){var I=b.random(c);return $APP.yt.j?$APP.yt.j(I):$APP.yt.call(null,
I)}());for(m=0;;)if(m<c)f[m]=l[m],m+=1;else break;JO(g,e,d);l=$APP.Td($APP.Jn,g);d=cO(oO(a,c-l,b));a=cO(rO(a,l,b));KO(c,g,d,a,k);return new $APP.n(null,3,[LO,f,MO,g,NO,k],null)},YO=function(a,b,c,d){c=$APP.Df.C(function(){var e=$APP.uq.j(b),f=$APP.op.j(b),g=$APP.ip.j(b);f=OO(a,d,e,f,g);var k=$APP.Qe(f);f=$APP.P(k,LO);g=$APP.P(k,MO);var l=$APP.P(k,NO);k=vO(b,f,l,e);if(k=wO(b,k))a:{var m=vO(b,f,l,e);if(wO(b,m)){var q=new Float64Array(e);for(var r=new Int32Array(e),v=$APP.rf(0),w=$APP.rf(0),y=0;;)if(y<
e){var A=Math.max($APP.No.j(b)-f[y],0),C=Math.max($APP.Ep.j(b)-f[y],0),I=l[y],J=g[y];q[y]=Math.min(I,A);r[y]=I<=A?1:0;I>C&&(J===0?$APP.ri.C(v,$APP.Hc):$APP.ri.C(w,$APP.Hc));y+=1}else break;q=new $APP.n(null,4,[yO,q,PO,r,QO,$APP.u(v),RO,$APP.u(w)],null);w=$APP.Qe(q);q=$APP.P(w,yO);r=$APP.P(w,PO);v=$APP.P(w,QO);w=$APP.P(w,RO);A=lO($APP.Z.j?$APP.Z.j(q):$APP.Z.call(null,q),$APP.Z.j?$APP.Z.j(r):$APP.Z.call(null,r),$APP.Z.j?$APP.Z.j(g):$APP.Z.call(null,g));y=$APP.O(A,0,null);A=$APP.O(A,1,null);q=new $APP.n(null,
6,[SO,y,xO,A,yO,q,zO,r,QO,v,RO,w],null);if(AO(b,q)){e=IO(b,f,l,g,e);e=$APP.$n.K($APP.N([$APP.hh([$APP.Qo,HO,SO,TO,UO,VO,$APP.Up,xO,$APP.Hp,GO],[$APP.Qo.j(e),HO.j(e),SO.j(q),FO.j(e),RO.j(q),QO.j(q),sO.j(m),xO.j(q),tO.j(m),GO.j(e)]),$APP.p($APP.zr.j(b))?new $APP.n(null,1,[$APP.tq,uO.j(m)],null):null]));break a}}e=null}else e=null;return new $APP.n(null,2,[WO,k,XO,e],null)},$APP.Fh(0,c,1));return new $APP.T(null,2,5,$APP.U,[$APP.pf(XO,c),$APP.Td($APP.Jn,$APP.Df.C(function(e){return $APP.p(WO.j(e))?1:
0},c))],null)},iP=function(a,b,c,d,e,f,g,k,l){return $APP.$n.K($APP.N([d,$APP.hh([$APP.Mr,ZO,$O,aP,$APP.Xp,bP,cP,dP,eP,fP,$APP.io,$APP.Rq,$APP.sp,gP,hP],[$APP.nd(g)?NaN:$APP.G($APP.Ff(function(m){return m<.636},g))/$APP.G(g),function(){var m=$APP.Df.C(VO,a);m=e.j?e.j(m):e.call(null,m);return $APP.xt.j?$APP.xt.j(m):$APP.xt.call(null,m)}(),l,1-$APP.G($APP.Ff(TO,a))/l,k/l,function(){var m=$APP.Df.C(xO,a);m=e.j?e.j(m):e.call(null,m);return $APP.xt.j?$APP.xt.j(m):$APP.xt.call(null,m)}(),l,function(){var m=
$APP.Df.C(UO,a);m=e.j?e.j(m):e.call(null,m);return $APP.xt.j?$APP.xt.j(m):$APP.xt.call(null,m)}(),function(){var m=$APP.Df.C(SO,a);m=e.j?e.j(m):e.call(null,m);return $APP.xt.j?$APP.xt.j(m):$APP.xt.call(null,m)}(),c,$APP.nd(f)?NaN:function(){var m=e.j?e.j(f):e.call(null,f);return $APP.xt.j?$APP.xt.j(m):$APP.xt.call(null,m)}(),$APP.nd(g)?NaN:function(){var m=e.j?e.j(g):e.call(null,g);return $APP.xt.j?$APP.xt.j(m):$APP.xt.call(null,m)}(),l/b,$APP.G($APP.Ff(TO,a))/l,b])]))},jP=function(a,b,c,d){var e=
$APP.G(a),f=$APP.Ff(function(l){return $APP.Ia(Number.isNaN(l))},$APP.Df.C(GO,a)),g=$APP.Ff(function(l){return $APP.Ia(Number.isNaN(l))},$APP.Df.C($APP.Qo,a)),k=$APP.G($APP.Ff(function(l){var m=TO.j(l);return $APP.p(m)?$APP.Qo.j(l)<.636:m},a));return iP(a,b,c,d,function(l){l=$APP.ye(l);return $APP.Z.j?$APP.Z.j(l):$APP.Z.call(null,l)},f,g,k,e)},kP=function(a,b,c){for(var d=new Float64Array(a*b),e=0;;)if($APP.D(c)){var f=$APP.E(c),g=$APP.O(f,0,null),k=$APP.O(f,1,null);f=$APP.O(f,2,null);if(f>0){for(var l=
a,m=0;;)if(m<l){for(var q=f,r=0;;)if(r<q)d[m*b+e+r]=g+Math.random()*(k-g),r+=1;else break;m+=1}else break;e+=f;c=$APP.Ac(c)}else c=$APP.Ac(c)}else{for(g=0;;)if(g<a)k=g*b,f=k+b,l=d.slice(k,f),l.sort(function(){return function(v,w){return v-w}}(g,e,c,k,f,l,a,d)),d.set(l,k),g+=1;else break;return d}},lP=function(a,b,c){var d=a.length;if(d===0)return 1;for(var e=new Int32Array(d),f=0;;)if(f<d)e[f]=f,f+=1;else break;e.sort(function(q,r){return a[q]-a[r]});f=0;for(var g=1;;)if(f<d){var k=e[f],l=a[k],m=
d-f;if(b[k]===1&&l<=c)g*=1-1/m,f+=1;else{if(l>c)return g;f+=1}}else return g},mP=function(a){for(var b=a.length-1;;)if(b>0){var c=Math.floor(Math.random()*(b+1)),d=a[b];a[b]=a[c];a[c]=d;--b}else break},rP=function(a){var b=$APP.Qe(a);a=$APP.P(b,$APP.Pp);var c=$APP.P(b,$APP.Gr),d=$APP.P(b,$APP.dr);$APP.P(b,$APP.Ur);var e=$APP.P(b,$APP.nr),f=a/Math.pow(Math.log(2),1/c),g=$APP.Td($APP.Jn,$APP.Df.C(function(ua){return $APP.Tc(ua,2)},$APP.ip.j(e))),k=$APP.Zd(g,2),l=kP(d,g,$APP.ip.j(e));b=new Int32Array(d);
for(var m=new Int32Array(d),q=new Int32Array(d),r=new Int32Array(d),v=new Uint8Array(d),w=$APP.No.j(e),y=$APP.Ep.j(e),A=$APP.ur.j(e),C=$APP.gq.j(e),I=1/c,J=0;;)if(J<d){for(var K=J*g,M=new Float64Array(g),W=new Int8Array(g),V=new Int8Array(g),xa=k,ea=0;;)if(ea<xa)V[ea]=1,ea+=1;else break;mP(V);xa=g;for(ea=0;;)if(ea<xa){var wa=l[K+ea],fa=f*Math.pow(-Math.log(1-Math.random()),I),za=Math.max(w-wa,0),ha=Math.max(y-wa,0);wa=Math.max(A-wa,0);fa<=za&&(b[J]+=1,V[ea]===1&&(r[J]+=1));fa<=ha&&(m[J]+=1);fa<=wa&&
(q[J]+=1);M[ea]=Math.min(fa,za);W[ea]=fa<=za?1:0;ea+=1}else break;lP(M,W,C)>.5&&(v[J]=1);J+=1}else break;f=$APP.wp.j(e);g=$APP.po.j(e);k=$APP.Mp.j(e);J=$APP.ks.j(e);e=$APP.rf(0);l=$APP.rf(0);w=$APP.rf(0);y=$APP.rf(0);A=$APP.rf(0);K=$APP.rf(0);I=$APP.rf(0);C=$APP.rf(0);for(M=0;;)if(M<d)ea=b[M],V=m[M],xa=v[M]===1,W=V-ea,V=q[M]-V,xa=r[M]<ea/(J+1)*J&&xa,$APP.ri.J(K,$APP.Jn,ea),$APP.ri.J(I,$APP.Jn,W),$APP.ri.J(C,$APP.Jn,V),xa&&$APP.ri.C(l,$APP.Hc),ea=ea<=f,W=W<=g,V=V<=k,ea&&$APP.ri.C(w,$APP.Hc),W&&$APP.ri.C(y,
$APP.Hc),V&&$APP.ri.C(A,$APP.Hc),xa&&ea&&W&&V&&$APP.ri.C(e,$APP.Hc),M+=1;else break;b=$APP.u(K)/d;m=$APP.u(I)/d;q=$APP.u(C)/d;r=Math.max(Math.abs(b-f),Math.abs(m-g),Math.abs(q-k));return $APP.hh([nP,oP,$APP.er,$APP.eq,pP,$APP.Pp,$APP.zp,$APP.Gr,$APP.no,qP,$APP.Yr],[$APP.u(y)/d,$APP.u(l)/d,r,m,$APP.u(A)/d,a,b,c,$APP.u(e)/d,$APP.u(w)/d,q])},aO=function aO(a,b){return $N($APP.Sn.C(aO,a),a,b)},NO=new $APP.Q(null,"survival-times","survival-times",1104744121),WO=new $APP.Q(null,"passed-screening","passed-screening",
-970442882),tO=new $APP.Q(null,"n-up","n-up",1244727544),HO=new $APP.Q(null,"z-final","z-final",1830128043),eO=new $APP.Q(null,"sum-control","sum-control",-918014575),MO=new $APP.Q(null,"arms-array","arms-array",-819399838),CO=new $APP.Q(null,"ev-fin","ev-fin",675117895),aP=new $APP.Q(null,"p-no-readout","p-no-readout",1519656388),yO=new $APP.Q(null,"time-ia","time-ia",-1902843318),FO=new $APP.Q(null,"reached","reached",826384279),LO=new $APP.Q(null,"enroll-times","enroll-times",-796557014),QO=new $APP.Q(null,
"alive-bat","alive-bat",-575070135),BO=new $APP.Q(null,"time-fin","time-fin",-811075357),dP=new $APP.Q(null,"median-gps-alive-upd","median-gps-alive-upd",1199822E3),eP=new $APP.Q(null,"median-z-ia","median-z-ia",276344881),hP=new $APP.Q(null,"n-attempts","n-attempts",-2026068801),fP=new $APP.Q(null,"n-pass-events","n-pass-events",1361985171),iO=new $APP.Q(null,"log-hr-num","log-hr-num",-863400848),qP=new $APP.Q(null,"p_ev_ia_le_60","p_ev_ia_le_60",939381615),bP=new $APP.Q(null,"median-hr-ia","median-hr-ia",
-584537370),cP=new $APP.Q(null,"n-pass-futility","n-pass-futility",-1718782803),SO=new $APP.Q(null,"z-ia","z-ia",-1345120916),uO=new $APP.Q(null,"n-pr3","n-pr3",-1020311282),VO=new $APP.Q(null,"bat-alive-upd","bat-alive-upd",-948525808),jO=new $APP.Q(null,"log-hr-den","log-hr-den",-376003383),zO=new $APP.Q(null,"ev-ia","ev-ia",1539100546),nP=new $APP.Q(null,"p_inc_upd_le_12","p_inc_upd_le_12",-642152286),pP=new $APP.Q(null,"p_inc_pr3_le_6","p_inc_pr3_le_6",-150583961),EO=new $APP.Q(null,"t-now","t-now",
-1553436397),gP=new $APP.Q(null,"p-reach80","p-reach80",-1229152388),dO=new $APP.Q(null,"sum-exp","sum-exp",-2061498251),xO=new $APP.Q(null,"hr-ia","hr-ia",608696309),$O=new $APP.Q(null,"n-accepted","n-accepted",-1920065151),oP=new $APP.Q(null,"p_pass_ia","p_pass_ia",-1033186493),UO=new $APP.Q(null,"gps-alive-upd","gps-alive-upd",-597652562),hO=new $APP.Q(null,"v","v",21465059),gO=new $APP.Q(null,"u","u",-1156634785),TO=new $APP.Q(null,"reached-80","reached-80",356081933),XO=new $APP.Q(null,"stats",
"stats",-85643011),RO=new $APP.Q(null,"alive-gps","alive-gps",-1734044909),sO=new $APP.Q(null,"n-ia","n-ia",440915214),ZO=new $APP.Q(null,"median-bat-alive-upd","median-bat-alive-upd",-1793961887),GO=new $APP.Q(null,"t80","t80",-1773986369),PO=new $APP.Q(null,"event-ia","event-ia",-188145433);console.log("CLJS Worker: Initializing");
self.onmessage=function(a){var b=a.data;a=b.id;var c=b.data;if($APP.H.C(b.type,"RUN_SIMULATION"))try{var d=$APP.qi(c,$APP.N([$APP.oi,!0]));if($APP.H.C($APP.Y.j(d),"RUN_STRESS_TEST"))var e=rP(d);else{var f=$APP.Qe(d),g=$APP.P(f,$APP.dp),k=$APP.P(f,$APP.As),l=$APP.P(f,$APP.dr),m=$APP.P(f,$APP.Ur),q=$APP.gt.random.default_rng(m),r=Math.min($APP.ns.j(k),l),v=YO(g,k,r,q),w=$APP.O(v,0,null),y=$APP.O(v,1,null);if($APP.G(w)>=$APP.mp.j(k)){d=l-r;var A=d>0?YO(g,k,d,q):new $APP.T(null,2,5,$APP.U,[$APP.Hf,0],
null),C=$APP.O(A,0,null),I=$APP.O(A,1,null),J=$APP.Cf.C(w,C);e=$APP.nd(J)?null:jP(J,l,y+I,g)}else e=null}var K=$APP.p(e)?bO(e):null;return self.postMessage($APP.fo(new $APP.n(null,4,[$APP.Bm,a,$APP.Y,"SIMULATION_RESULT",$APP.Wp,K,$APP.Nq,!0],null)))}catch(M){if(M instanceof Error)return K=M,console.error("Worker error:",K),self.postMessage($APP.fo(new $APP.n(null,4,[$APP.Bm,a,$APP.Y,"SIMULATION_RESULT",$APP.Ro,K.message,$APP.Nq,!1],null)));throw M;}else return null};
}).call(this);