(ns webr.r-base.core
  "R Base core namespace.
   Requires and re-exports all wrapped R base distribution and test functions."
  (:require [webr.r-base.unif :refer [dunif dunif-code dunif!
                                      punif punif-code punif!
                                      qunif qunif-code qunif!
                                      runif runif-code runif!]]
            [webr.r-base.discrete :refer [dbinom dbinom-code dbinom!
                                          pbinom pbinom-code pbinom!
                                          qbinom qbinom-code qbinom!
                                          rbinom rbinom-code rbinom!
                                          dpois dpois-code dpois!
                                          ppois ppois-code ppois!
                                          qpois qpois-code qpois!
                                          rpois rpois-code rpois!
                                          dnbinom dnbinom-code dnbinom!
                                          pnbinom pnbinom-code pnbinom!
                                          qnbinom qnbinom-code qnbinom!
                                          rnbinom rnbinom-code rnbinom!
                                          dgeom dgeom-code dgeom!
                                          pgeom pgeom-code pgeom!
                                          qgeom qgeom-code qgeom!
                                          rgeom rgeom-code rgeom!
                                          dhyper dhyper-code dhyper!
                                          phyper phyper-code phyper!
                                          qhyper qhyper-code qhyper!
                                          rhyper rhyper-code rhyper!]]
            [webr.r-base.continuous :refer [dnorm dnorm-code dnorm!
                                            pnorm pnorm-code pnorm!
                                            qnorm qnorm-code qnorm!
                                            rnorm rnorm-code rnorm!
                                            dt dt-code dt!
                                            pt pt-code pt!
                                            qt qt-code qt!
                                            rt rt-code rt!
                                            dchisq dchisq-code dchisq!
                                            pchisq pchisq-code pchisq!
                                            qchisq qchisq-code qchisq!
                                            rchisq rchisq-code rchisq!
                                            df-dist df-dist-code df-dist!
                                            pf pf-code pf!
                                            qf qf-code qf!
                                            rf rf-code rf!
                                            dexp dexp-code dexp!
                                            pexp pexp-code pexp!
                                            qexp qexp-code qexp!
                                            rexp rexp-code rexp!
                                            dgamma dgamma-code dgamma!
                                            pgamma pgamma-code pgamma!
                                            qgamma qgamma-code qgamma!
                                            rgamma rgamma-code rgamma!
                                            dbeta dbeta-code dbeta!
                                            pbeta pbeta-code pbeta!
                                            qbeta qbeta-code qbeta!
                                            rbeta rbeta-code rbeta!
                                            dweibull dweibull-code dweibull!
                                            pweibull pweibull-code pweibull!
                                            qweibull qweibull-code qweibull!
                                            rweibull rweibull-code rweibull!
                                            dlnorm dlnorm-code dlnorm!
                                            plnorm plnorm-code plnorm!
                                            qlnorm qlnorm-code qlnorm!
                                            rlnorm rlnorm-code rlnorm!]]
            [webr.r-base.tests :refer [t-test t-test-code t-test!
                                       wilcox-test wilcox-test-code wilcox-test!
                                       aov aov-code aov!
                                       kruskal-test kruskal-test-code kruskal-test!
                                       friedman-test friedman-test-code friedman-test!
                                       chisq-test chisq-test-code chisq-test!
                                       fisher-test fisher-test-code fisher-test!
                                       prop-test prop-test-code prop-test!
                                       binom-test binom-test-code binom-test!
                                       mcnemar-test mcnemar-test-code mcnemar-test!
                                       cor-test cor-test-code cor-test!
                                       shapiro-test shapiro-test-code shapiro-test!
                                       var-test var-test-code var-test!
                                       bartlett-test bartlett-test-code bartlett-test!
                                       fligner-test fligner-test-code fligner-test!
                                       ansari-test ansari-test-code ansari-test!
                                       ks-test ks-test-code ks-test!
                                       box-test box-test-code box-test!
                                       mauchly-test mauchly-test-code mauchly-test!]]))
